# Predicting Sales for ZS Data Science Challenge
https://www.hackerearth.com/challenge/competitive/zs-data-science-challenge-2018
Our job is to predict monthly sales for various countries selling different products.

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

Parameters currently in use:

{'bootstrap': True,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': 1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

## Reading  and manipulating train.csv
There are couple of csv files namely yds_train2018.csv,promotional_expenses.csv,holidays.xlsx,yds_test2018.csv.
At first we will read yds_train2018.csv int panda DataFrame which contains features **Year**,**Month**,**week**,etc.
As we have to predict monthly sales we will sum up weekly sales to monthly sales.

In [4]:
df_train=pd.read_csv('yds_train2018.csv')
unique_year=df_train.loc[:,'Year'].unique()
unique_month=df_train.loc[:,'Month'].unique()
print(unique_month)
unique_product=df_train.loc[:,'Product_ID'].unique()
unique_country=df_train.loc[:,'Country'].unique()
temp=pd.DataFrame(columns=['Year','Month','Product_ID','Country','Sales_sum'])
print(df_train.Sales.dtype)
i=0
for year in unique_year:
    for month in unique_month:
        for country in unique_country:
            for product in unique_product:
                sum_sales=df_train.loc[(df_train.Year==year)&(df_train.Month==month)&(df_train.Product_ID==product)&(df_train.Country==country),'Sales'].sum()
                ls=[]
                ls.extend((int(year),int(month),int(product),country,sum_sales))
            #print(ls)
                series=pd.Series(ls,index=['Year','Month','Product_ID','Country','Sales_sum'])
            #print(series)
                temp=temp.append(series,ignore_index=True)
            
            #i=i+1
temp.Year=temp.Year.astype('int64')
temp.Month=temp.Month.astype('int64')
temp.Product_ID=temp.Product_ID.astype('int64')
#Dropping row for which sales_sum is zero.
temp=temp.loc[temp.Sales_sum!=0,:]
temp = temp.reset_index(drop=True)
print(temp.head())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
float64
   Year  Month  Product_ID    Country    Sales_sum
0  2013      1           1  Argentina  34346025.00
1  2013      1           2  Argentina   2751851.48
2  2013      1           3  Argentina         0.00
3  2013      1           5  Argentina         0.00
4  2013      1           4  Argentina         0.00
float64
   Year  Month  Product_ID    Country    Sales_sum
0  2013      1           1  Argentina  34346025.00
1  2013      1           2  Argentina   2751851.48
2  2013      1           2    Belgium    314850.13
3  2013      1           1   Columbia   3947356.31
4  2013      1           2   Columbia   2885137.06

## Reading promotion_expense.csv and merging it with above dataframe.

In [5]:
df_expenses=pd.read_csv('promotional_expense.csv')
df_expenses.columns=['Year','Month','Country','Product_ID','Expense_Price']
df_merge1=df_expenses.merge(temp,how='inner',on=['Year','Month','Product_ID','Country'])
print(df_merge1.head())

     Year  Month    Country  Product_ID  Expense_Price    Sales_sum
0    2013      1  Argentina           1      14749.307  34346025.00
1    2013      1  Argentina           2       1329.374   2751851.48
2    2013      2  Argentina           1      12187.566  32005575.00
3    2013      2  Argentina           2       1315.006   2804313.12
4    2013      3  Argentina           1      13076.579  32530050.00
5    2013      3  Argentina           2       1192.655   2573004.98
6    2013      4  Argentina           1      14377.199  35588700.00
7    2013      4  Argentina           2       1658.633   3436237.42
8    2013      5  Argentina           1      15652.861  38789100.00
9    2013      5  Argentina           2       1838.573   3772468.84
10   2013      6  Argentina           1      11718.545  36196650.00
11   2013      6  Argentina           2       1569.111   3712853.34
12   2013      7  Argentina           1      14144.888  37133775.00
13   2013      7  Argentina           2       1812.946   3791545.80
14   2013      8  Argentina           1      12839.791  35311500.00
15   2013      8  Argentina           2       1763.468   3698545.62
16   2013      9  Argentina           1      10788.309  38437875.00
17   2013      9  Argentina           2       1809.594   3979930.78
18   2013     10  Argentina           1      16108.134  44397675.00
19   2013     10  Argentina           2       2051.441   4514085.66
20   2013     11  Argentina           1      16242.067  45525375.00
21   2013     11  Argentina           2       2594.987   5258087.10
22   2013     12  Argentina           1      11144.301  33610500.00
23   2013     12  Argentina           2       1774.795   4010930.84
24   2014      1  Argentina           1      15316.880  44600850.00
25   2014      1  Argentina           2       2218.769   4821701.64
26   2014      2  Argentina           1      14746.595  41562675.00
27   2014      2  Argentina           2       1763.443   4044315.52
28   2014      3  Argentina           1      12998.792  36957375.00
29   2014      3  Argentina           2       2222.233   4945701.88
..    ...    ...        ...         ...            ...          ...
306  2013      5    Finland           4       1513.342  32942280.96
307  2013      6    Finland           4        921.716  19155934.08
308  2013      7    Finland           4       1265.548  27180092.16
309  2013      8    Finland           4       1280.376  27492566.40
310  2013      9    Finland           4       1554.288  33901217.28
311  2013     10    Finland           4       1389.610  30052978.56
312  2013     11    Finland           4       1701.203  37328238.72
313  2013     12    Finland           4       1211.026  25899212.16
314  2014      1    Finland           4       1320.833  28468419.84
315  2014      2    Finland           4        881.556  18218511.36
316  2014      3    Finland           4       1583.462  39838901.76
317  2014      4    Finland           4       1522.261  33158501.77
318  2014      5    Finland           4       1121.180  23801300.73
319  2014      6    Finland           4       1348.254  27895262.62
320  2014      7    Finland           4       1392.341  30143145.19
321  2014      8    Finland           4       1242.183  26633523.87
322  2014      9    Finland           4       1732.551  38019992.88
323  2014     10    Finland           4       1115.553  23672488.22
324  2014     11    Finland           4       1169.936  25217203.55
325  2014     12    Finland           4       1402.402  30169071.14
326  2015      1    Finland           4       1416.856  30706372.78
327  2015      2    Finland           4       1206.613  50113926.02
328  2015      3    Finland           4       1588.459   9044923.37
329  2015      4    Finland           4       1432.277  31067217.98
330  2015      5    Finland           4       1148.367  24446467.61
331  2015      6    Finland           4       1517.116  31931776.30
332  2015      7    Finland           4       1313.673  28287106.21
333  2015      8    Finland           4       1334.374  28765114.99
334  2015      9    Finland           4       1350.590  28817795.16
335  2015     10    Finland           4       1441.062  31268810.86

[336 rows x 6 columns]

## Now we will read holidays.xlsx file
We will count the number of holidays in a given month,year. This will turn out to be useful feature.

In [7]:
df_holidays=pd.read_excel('holidays.xlsx')
print(df_holidays.shape)
# Date is in format YYYY, MM, DD. So we will seperate it.
df_holidays['Year'],df_holidays['Month'],df_holidays['date']=df_holidays['Date'].str.split(', ').str
print(df_holidays.shape)
#Now date column is no more neede.
df_holidays=df_holidays.drop(columns=['Date'])

(652, 6)

Here we will count number holidays in a given (year,month,country) and append it as feature no_of_holidays

In [9]:
unique_year=df_holidays.Year.unique()
unique_month=['1','2','3','4','5','6','7','8','9','10','11','12']
print(unique_month)
unique_country=df_holidays.Country.unique()
holidays_count=pd.DataFrame(columns=['Year','Month','Country','no_of_holidays'])
for year in unique_year:
    for month in unique_month:
        for country in unique_country:
            count=df_holidays.loc[(df_holidays.Year==year)&(df_holidays.Month==month)&(df_holidays.Country==country),'date'].nunique()
            #if year==2016 and country=='England':
                #print(count,month,year,country)
            ls=[]
            ls.extend((year,month,str(country),int(count)))
            series=pd.Series(ls,index=['Year','Month','Country','no_of_holidays'])
            #print(series.dtype)
            #print(series)
            holidays_count=holidays_count.append(series,ignore_index=True)
print(df_merge1.Country.dtype)
holidays_count.no_of_holidays=holidays_count.no_of_holidays.astype('int64')
holidays_count.Year=holidays_count.Year.astype('int64')
holidays_count.Month=holidays_count.Month.astype('int64')

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
object

Merging the holidays information with main DataFrame.

In [10]:
df_merged_holidays=df_merge1.merge(holidays_count,how='inner',on=['Year','Month','Country'])
print(df_merged_holidays.head())
df_merged_holidays.Year=df_merged_holidays.Year.astype('int64')

   Year  Month    Country  Product_ID  Expense_Price    Sales_sum  \
0  2013      1  Argentina           1      14749.307  34346025.00
1  2013      1  Argentina           2       1329.374   2751851.48
2  2013      2  Argentina           1      12187.566  32005575.00
3  2013      2  Argentina           2       1315.006   2804313.12
4  2013      3  Argentina           1      13076.579  32530050.00
5  2013      3  Argentina           2       1192.655   2573004.98
6  2013      4  Argentina           1      14377.199  35588700.00
7  2013      4  Argentina           2       1658.633   3436237.42
8  2013      5  Argentina           1      15652.861  38789100.00
9  2013      5  Argentina           2       1838.573   3772468.84

   no_of_holidays
0               1
1               1
2               2
3               2
4               4
5               4
6               1
7               1
8               2
9               2
[2013 2014 2015 2016]
['Argentina' 'Belgium' 'Columbia' 'Denmark' 'England' 'Finland']
72    1
73    1
74    2
75    2
76    3
77    3
Name: Month, dtype: int64

Converting categoricals values into numeric.(Could have used panda.factorize method)

In [11]:
df_merged_holidays.loc[df_merged_holidays.Year==2013,'Year']=1
df_merged_holidays.loc[df_merged_holidays.Year==2014,'Year']=2
df_merged_holidays.loc[df_merged_holidays.Year==2015,'Year']=3
df_merged_holidays.loc[df_merged_holidays.Year==2016,'Year']=4
df_merged_holidays.loc[df_merged_holidays.Country=='Argentina','Country']=1
df_merged_holidays.loc[df_merged_holidays.Country=='Belgium','Country']=2
df_merged_holidays.loc[df_merged_holidays.Country=='Columbia','Country']=3
df_merged_holidays.loc[df_merged_holidays.Country=='Denmark','Country']=4
df_merged_holidays.loc[df_merged_holidays.Country=='England','Country']=5
df_merged_holidays.loc[df_merged_holidays.Country=='Finland','Country']=6

Expense and sales were in local currency so converted it into one scale i.e USD)

In [12]:
df_merged_holidays.loc[df_merged_holidays.Country==1,'Sales_sum']*=0.036
df_merged_holidays.loc[df_merged_holidays.Country==1,'Expense_Price']*=0.036
df_merged_holidays.loc[df_merged_holidays.Country==2,'Sales_sum']*=1.17
df_merged_holidays.loc[df_merged_holidays.Country==2,'Expense_Price']*=1.17
df_merged_holidays.loc[df_merged_holidays.Country==3,'Sales_sum']*=0.00035
df_merged_holidays.loc[df_merged_holidays.Country==3,'Expense_Price']*=0.00035
df_merged_holidays.loc[df_merged_holidays.Country==4,'Sales_sum']*=0.16
df_merged_holidays.loc[df_merged_holidays.Country==4,'Expense_Price']*=0.16
df_merged_holidays.loc[df_merged_holidays.Country==5,'Sales_sum']*=1.31
df_merged_holidays.loc[df_merged_holidays.Country==5,'Expense_Price']*=1.31
df_merged_holidays.loc[df_merged_holidays.Country==6,'Sales_sum']*=1.17
df_merged_holidays.loc[df_merged_holidays.Country==6,'Expense_Price']*=1.17
#df_merged_holidays[['Year','Country']] = df_merged_holidays[['Year','Country']].stack().rank(method='dense').unstack()
print(df_merged_holidays.head())

     Year  Month  Country  Product_ID  Expense_Price     Sales_sum  \
0       1      1        1           1     530.975052  1.236457e+06
1       1      1        1           2      47.857464  9.906665e+04
2       1      2        1           1     438.752376  1.152201e+06
3       1      2        1           2      47.340216  1.009553e+05
4       1      3        1           1     470.756844  1.171082e+06
5       1      3        1           2      42.935580  9.262818e+04
6       1      4        1           1     517.579164  1.281193e+06
7       1      4        1           2      59.710788  1.237045e+05
8       1      5        1           1     563.502996  1.396408e+06
9       1      5        1           2      66.188628  1.358089e+05
10      1      6        1           1     421.867620  1.303079e+06
11      1      6        1           2      56.487996  1.336627e+05
12      1      7        1           1     509.215968  1.336816e+06
13      1      7        1           2      65.266056  1.364956e+05
14      1      8        1           1     462.232476  1.271214e+06
15      1      8        1           2      63.484848  1.331476e+05
16      1      9        1           1     388.379124  1.383764e+06
17      1      9        1           2      65.145384  1.432775e+05
18      1     10        1           1     579.892824  1.598316e+06
19      1     10        1           2      73.851876  1.625071e+05
20      1     11        1           1     584.714412  1.638913e+06
21      1     11        1           2      93.419532  1.892911e+05
22      1     12        1           1     401.194836  1.209978e+06
23      1     12        1           2      63.892620  1.443935e+05
24      2      1        1           1     551.407680  1.605631e+06
25      2      1        1           2      79.875684  1.735813e+05
26      2      2        1           1     530.877420  1.496256e+06
27      2      2        1           2      63.483948  1.455954e+05
28      2      3        1           1     467.956512  1.330466e+06
29      2      3        1           2      80.000388  1.780453e+05
..    ...    ...      ...         ...            ...           ...
306     1      5        6           4    1770.610140  3.854247e+07
307     1      6        6           4    1078.407720  2.241244e+07
308     1      7        6           4    1480.691160  3.180071e+07
309     1      8        6           4    1498.039920  3.216630e+07
310     1      9        6           4    1818.516960  3.966442e+07
311     1     10        6           4    1625.843700  3.516198e+07
312     1     11        6           4    1990.407510  4.367404e+07
313     1     12        6           4    1416.900420  3.030208e+07
314     2      1        6           4    1545.374610  3.330805e+07
315     2      2        6           4    1031.420520  2.131566e+07
316     2      3        6           4    1852.650540  4.661152e+07
317     2      4        6           4    1781.045370  3.879545e+07
318     2      5        6           4    1311.780600  2.784752e+07
319     2      6        6           4    1577.457180  3.263746e+07
320     2      7        6           4    1629.038970  3.526748e+07
321     2      8        6           4    1453.354110  3.116122e+07
322     2      9        6           4    2027.084670  4.448339e+07
323     2     10        6           4    1305.197010  2.769681e+07
324     2     11        6           4    1368.825120  2.950413e+07
325     2     12        6           4    1640.810340  3.529781e+07
326     3      1        6           4    1657.721520  3.592646e+07
327     3      2        6           4    1411.737210  5.863329e+07
328     3      3        6           4    1858.497030  1.058256e+07
329     3      4        6           4    1675.764090  3.634865e+07
330     3      5        6           4    1343.589390  2.860237e+07
331     3      6        6           4    1775.025720  3.736018e+07
332     3      7        6           4    1536.997410  3.309591e+07
333     3      8        6           4    1561.217580  3.365518e+07
334     3      9        6           4    1580.190300  3.371682e+07
335     3     10        6           4    1686.042540  3.658451e+07

     no_of_holidays
0                 1
1                 1
2                 2
3                 2
4                 4
5                 4
6                 1
7                 1
8                 2
9                 2
10                2
11                2
12                1
13                1
14                1
15                1
16                0
17                0
18                1
19                1
20                1
21                1
22                2
23                2
24                1
25                1
26                0
27                0
28                3
29                3
..              ...
306               3
307               2
308               0
309               0
310               0
311               0
312               1
313               4
314               2
315               0
316               0
317               3
318               2
319               3
320               0
321               0
322               0
323               0
324               1
325               4
326               2
327               0
328               0
329               3
330               3
331               2
332               0
333               0
334               0
335               1

[336 rows x 7 columns]

## Scaling values using min-max scaler
Only for linear models and neural network(not necessary for tree based models)

In [14]:
scaler = MinMaxScaler()
df_merged=df_merged_holidays.drop(columns=['Sales_sum'])
nparray=df_merged.values.ravel()
rf_X=df_merged.values.ravel().reshape(-1,6)
nparray=nparray.reshape(-1,6)
print(nparray.shape)
#print(nparray)
scaler.fit(nparray)
final_data=scaler.transform(nparray)
#print("Break")
#print(scaler.inverse_transform(x))
scaler2 = MinMaxScaler()
y_array=df_merged_holidays.Sales_sum.values
rf_y=y_array.reshape(-1,1)
y_array=y_array.reshape(-1,1)
scaler2.fit(y_array)
y_array=scaler2.transform(y_array)
print(y_array)

(336, 6)
[[2.10734635e-02]
 [1.67480737e-03]
 [1.96364395e-02]
 [1.70701854e-03]
 [1.99584644e-02]
 [1.56499656e-03]
 [2.18364594e-02]
 [2.09501673e-03]
 [2.38014881e-02]
 [2.30146106e-03]
 [2.22097375e-02]
 [2.26485745e-03]
 [2.27851273e-02]
 [2.31317421e-03]
 [2.16662601e-02]
 [2.25607259e-03]
 [2.35858378e-02]
 [2.42884159e-03]
 [2.72451237e-02]
 [2.75680988e-03]
 [2.79375255e-02]
 [3.21362284e-03]
 [2.06218550e-02]
 [2.44787547e-03]
 [2.73698720e-02]
 [2.94568447e-03]
 [2.55044486e-02]
 [2.46837348e-03]
 [2.26768186e-02]
 [3.02181996e-03]
 [2.66619975e-02]
 [3.09649131e-03]
 [2.50750821e-02]
 [3.54159112e-03]
 [2.47762662e-02]
 [3.63676049e-03]
 [2.66687668e-02]
 [3.42006716e-03]
 [2.53448867e-02]
 [3.28097347e-03]
 [2.68679774e-02]
 [3.43470860e-03]
 [2.68641092e-02]
 [3.95155148e-03]
 [2.60034421e-02]
 [3.93544589e-03]
 [2.71503536e-02]
 [3.54598356e-03]
 [2.85854435e-02]
 [3.60747761e-03]
 [2.02891927e-02]
 [3.69679040e-03]
 [2.32338347e-02]
 [3.98669094e-03]
 [2.15589184e-02]
 [4.11553562e-03]
 [2.18219538e-02]
 [3.69386211e-03]
 [2.56233947e-02]
 [4.20045598e-03]
 [2.03182039e-02]
 [4.69387255e-03]
 [1.46552077e-02]
 [3.98376265e-03]
 [1.52828178e-02]
 [4.30880264e-03]
 [1.00424188e-02]
 [4.55770714e-03]
 [9.04926695e-03]
 [4.79929092e-03]
 [9.19722433e-03]
 [3.93398175e-03]
 [9.03572837e-03]
 [4.61188048e-03]
 [6.87052199e-03]
 [4.47864336e-03]
 [9.20496066e-03]
 [4.56356372e-03]
 [6.26796550e-03]
 [8.66923761e-03]
 [5.34692963e-03]
 [9.19554383e-03]
 [9.26133210e-03]
 [8.04424898e-03]
 [1.33402053e-02]
 [9.52448521e-03]
 [1.09718273e-02]
 [1.17941808e-02]
 [1.01165797e-02]
 [1.11362980e-02]
 [1.23862753e-02]
 [1.48204415e-02]
 [1.12678746e-02]
 [1.82414319e-02]
 [1.55112184e-02]
 [1.10797087e-02]
 [2.41952710e-02]
 [1.32744170e-02]
 [1.61033129e-02]
 [1.61362070e-02]
 [2.14979516e-02]
 [2.31426585e-02]
 [1.53138536e-02]
 [1.81755892e-02]
 [2.00177154e-02]
 [2.29781878e-02]
 [1.94256209e-02]
 [2.25505640e-02]
 [2.72873200e-02]
 [2.41952710e-02]
 [1.68927722e-02]
 [2.51163068e-02]
 [2.31037837e-02]
 [3.31155632e-02]
 [1.93847556e-02]
 [2.16812579e-02]
 [2.84100730e-02]
 [8.74838008e-06]
 [2.40757568e-06]
 [9.50480303e-06]
 [0.00000000e+00]
 [1.01933712e-05]
 [2.02884227e-06]
 [1.04314551e-05]
 [3.98537060e-06]
 [1.17621644e-05]
 [5.41672926e-06]
 [8.31017797e-06]
 [4.53803458e-06]
 [1.03422750e-05]
 [9.81408983e-06]
 [2.66480788e-06]
 [4.49723903e-06]
 [6.00774390e-06]
 [7.00220010e-06]
 [1.06325805e-05]
 [8.08034505e-06]
 [9.32077535e-06]
 [1.01731418e-05]
 [9.07758973e-06]
 [9.77329428e-06]
 [9.45902107e-06]
 [1.45683885e-05]
 [1.21255437e-05]
 [1.28330332e-05]
 [1.23666843e-05]
 [1.14351734e-05]
 [1.11892000e-05]
 [1.61247287e-05]
 [1.40879237e-05]
 [1.73090563e-05]
 [1.23844545e-05]
 [1.85434850e-05]
 [1.38824609e-05]
 [2.07773756e-05]
 [2.76854334e-06]
 [1.77948631e-05]
 [6.94722515e-06]
 [2.07352843e-05]
 [6.55391741e-06]
 [2.12562228e-05]
 [4.70777499e-06]
 [1.88177656e-05]
 [6.06075898e-06]
 [2.21853821e-05]
 [7.36038757e-06]
 [2.55775543e-05]
 [6.59195343e-06]
 [1.98302225e-05]
 [1.28523515e-05]
 [2.82871813e-05]
 [8.69111355e-06]
 [2.30768561e-05]
 [6.94897120e-06]
 [2.27807742e-05]
 [1.07530521e-05]
 [2.63595448e-05]
 [9.53480311e-06]
 [2.91484453e-05]
 [3.40517465e-06]
 [2.07640752e-05]
 [4.83758094e-06]
 [2.67893411e-05]
 [9.46801754e-06]
 [2.48041597e-05]
 [6.88204207e-06]
 [2.86422408e-05]
 [6.48995471e-06]
 [2.57291769e-05]
 [4.96455656e-06]
 [2.82554241e-05]
 [6.77855661e-06]
 [2.34464809e-05]
 [2.66861892e-06]
 [2.94753293e-05]
 [2.77913659e-01]
 [2.30459191e-01]
 [2.43280136e-01]
 [2.70596934e-01]
 [2.89360002e-01]
 [2.37913485e-01]
 [3.18064883e-01]
 [2.52076731e-01]
 [2.59843283e-01]
 [2.87518668e-01]
 [2.66005638e-01]
 [2.16984813e-01]
 [3.44139226e-01]
 [2.38852749e-01]
 [2.73286382e-01]
 [2.79293875e-01]
 [2.82069350e-01]
 [3.33457032e-01]
 [3.68442921e-01]
 [3.22903136e-01]
 [3.57829866e-01]
 [3.73621386e-01]
 [3.23169258e-01]
 [3.91663463e-01]
 [3.65261275e-01]
 [3.38663412e-01]
 [4.25270115e-01]
 [4.25172358e-01]
 [3.74149211e-01]
 [5.18755471e-01]
 [3.47713115e-01]
 [4.65694621e-01]
 [4.83489097e-01]
 [4.43745653e-01]
 [4.68253945e-01]
 [5.43285612e-01]
 [3.44360597e-01]
 [4.80998098e-01]
 [5.34026213e-01]
 [3.71433181e-03]
 [1.03157404e-02]
 [3.12845670e-03]
 [9.25582023e-03]
 [3.54473661e-03]
 [9.81332093e-03]
 [3.99112026e-03]
 [1.12893727e-02]
 [3.91170801e-03]
 [1.09570790e-02]
 [4.92014152e-03]
 [1.23229805e-02]
 [3.14875114e-03]
 [1.05038606e-02]
 [3.12220591e-03]
 [9.22215934e-03]
 [3.44322665e-03]
 [1.06211120e-02]
 [4.00574214e-03]
 [1.13673396e-02]
 [4.33934443e-03]
 [1.29116889e-02]
 [4.46922926e-03]
 [1.31038436e-02]
 [3.10405904e-03]
 [1.02557678e-02]
 [3.21635936e-03]
 [1.04766879e-02]
 [3.89979472e-03]
 [1.17244830e-02]
 [4.04953383e-03]
 [1.24098782e-02]
 [3.36098002e-03]
 [1.24202827e-02]
 [3.65874391e-03]
 [1.17728236e-02]
 [4.04782396e-03]
 [1.41539742e-02]
 [3.10802150e-03]
 [1.04809715e-02]
 [3.86969367e-03]
 [1.24253013e-02]
 [3.76640523e-03]
 [1.23856785e-02]
 [3.83279109e-03]
 [1.56714739e-02]
 [4.24115212e-03]
 [1.56702578e-02]
 [4.34648021e-03]
 [1.39609917e-02]
 [2.58799356e-03]
 [1.16099692e-02]
 [3.82039877e-03]
 [1.43741340e-02]
 [3.91671610e-03]
 [1.56429664e-02]
 [3.25432701e-03]
 [1.25385409e-02]
 [3.75224450e-03]
 [1.41260268e-02]
 [4.51996302e-03]
 [1.69266769e-02]
 [2.61108753e-03]
 [1.03880390e-02]
 [3.89756403e-03]
 [1.39969965e-02]
 [3.66550388e-03]
 [1.39326043e-02]
 [3.02369078e-01]
 [3.29734983e-01]
 [5.63052231e-01]
 [4.49421122e-01]
 [6.57342762e-01]
 [3.82238570e-01]
 [5.42359271e-01]
 [5.48594641e-01]
 [6.76478172e-01]
 [5.99687228e-01]
 [7.44863799e-01]
 [5.16799530e-01]
 [5.68067630e-01]
 [3.63532460e-01]
 [7.94963650e-01]
 [6.61657412e-01]
 [4.74936067e-01]
 [5.56630375e-01]
 [6.01486487e-01]
 [5.31452595e-01]
 [7.58667634e-01]
 [4.72365635e-01]
 [5.03190165e-01]
 [6.02003835e-01]
 [6.12725597e-01]
 [1.00000000e+00]
 [1.80475083e-01]
 [6.19926202e-01]
 [4.87810261e-01]
 [6.37178315e-01]
 [5.64449547e-01]
 [5.73988131e-01]
 [5.75039354e-01]
 [6.23948953e-01]]

In [571]:
X=nparray
y=y_array
print(X.shape,y.shape)

(336, 6) (336, 1)

## Training RandomForestRegressor by getting best parametres using RandomSearchCV
Using RandomSearchCV to get best parameters for Random Forest and train the model using the data preprocessed.As data given only contained 336 training examples didn't split my training data into parts. Due to limited data and polynomial regression not giving score upto the mark decided to go with RandomForestRegressor.

In [ ]:
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [ ]:
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

In [19]:

rf_random.fit(rf_X,rf_y.ravel())

Fitting 3 folds for each of 100 candidates, totalling 300 fits

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   34.8s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  4.8min finished

RandomizedSearchCV(cv=3, error_score='raise',
          estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
          fit_params=None, iid=True, n_iter=100, n_jobs=-1,
          param_distributions={'bootstrap': [True, False], 'min_samples_leaf': [1, 2, 4], 'min_samples_split': [2, 5, 10], 'max_features': ['auto', 'sqrt'], 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None]},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring=None, verbose=2)

Can try polynomial regression with various degree of polynomial(Polynomial regression didn't lend me a good score)

In [572]:
from sklearn.metrics import mean_squared_error

model = make_pipeline(PolynomialFeatures(2), Ridge())
model.fit(X, y)
    #y_plot = model.predict(X_plot)
print ("Train Accuracy :: ", mean_squared_error(y, model.predict(X)))
output=scaler2.inverse_transform(model.predict(X).reshape(-1,1))
output=np.absolute(output)
print(output)
    #print ("Test Accuracy  :: ", accuracy_score(test_y, predictions))
    #print (" Confusion matrix \n", confusion_matrix(test_y, predictions))

Train Accuracy ::  0.01733070677682805
[[3.35109920e+06]
 [5.65503129e+06]
 [2.54100286e+06]
 [4.66535586e+06]
 [5.78865076e+05]
 [2.77451499e+06]
 [3.13159966e+06]
 [5.38608832e+06]
 [2.05098253e+06]
 [4.38271499e+06]
 [2.24642475e+06]
 [4.31980040e+06]
 [2.90224502e+06]
 [5.12947831e+06]
 [2.91233834e+06]
 [5.05105577e+06]
 [3.88382646e+06]
 [5.87467134e+06]
 [2.51811283e+06]
 [4.86693382e+06]
 [2.42676058e+06]
 [4.74670558e+06]
 [1.79544335e+06]
 [3.81383736e+06]
 [3.01154387e+06]
 [5.29278886e+06]
 [3.87861383e+06]
 [6.15175469e+06]
 [1.19358270e+06]
 [3.31116803e+06]
 [4.52275026e+04]
 [2.32350088e+06]
 [1.83272615e+06]
 [4.02768048e+06]
 [1.81472909e+06]
 [3.93725314e+06]
 [2.52799645e+06]
 [4.77700745e+06]
 [2.58088862e+06]
 [4.71031717e+06]
 [3.26575548e+06]
 [5.52369097e+06]
 [2.30971085e+06]
 [4.50487441e+06]
 [2.27802582e+06]
 [4.42680322e+06]
 [1.14015567e+06]
 [3.44346930e+06]
 [2.64673653e+06]
 [4.96545765e+06]
 [1.94553427e+06]
 [3.98116563e+06]
 [2.47675287e+06]
 [4.79464601e+06]
 [6.77986486e+05]
 [2.87982029e+06]
 [1.49394720e+06]
 [3.72822887e+06]
 [1.08949632e+06]
 [3.61180445e+06]
 [2.36343827e+06]
 [4.41541309e+06]
 [2.17772078e+06]
 [4.37592355e+06]
 [3.00737142e+06]
 [5.18181795e+06]
 [2.10348077e+06]
 [4.18641163e+06]
 [1.94842119e+06]
 [4.08805027e+06]
 [1.05800906e+06]
 [3.13658335e+06]
 [2.77210142e+06]
 [4.61929363e+06]
 [1.91296559e+06]
 [3.64353322e+06]
 [7.57114503e+05]
 [2.64040415e+06]
 [1.18224695e+06]
 [1.87222018e+06]
 [1.07095196e+06]
 [7.80323282e+05]
 [2.02503151e+06]
 [1.58972903e+06]
 [2.76706250e+05]
 [4.36004144e+05]
 [1.13046108e+06]
 [1.04960904e+06]
 [7.64753650e+05]
 [7.03523761e+03]
 [6.02907780e+05]
 [1.36945460e+06]
 [1.41536071e+06]
 [9.29458904e+05]
 [8.61196112e+05]
 [7.52683038e+05]
 [5.16105128e+05]
 [4.88540911e+04]
 [6.24414627e+05]
 [4.77633509e+05]
 [1.51397889e+06]
 [7.79182316e+05]
 [1.72930876e+05]
 [9.42078110e+05]
 [6.74404100e+05]
 [1.57541907e+06]
 [3.13999083e+06]
 [2.52382783e+05]
 [1.07088127e+06]
 [8.95511218e+05]
 [8.73969022e+04]
 [2.58101650e+05]
 [2.34898341e+06]
 [1.73717610e+06]
 [4.31326446e+05]
 [3.10299933e+05]
 [1.99478031e+06]
 [4.50853313e+06]
 [3.15033713e+06]
 [2.77294622e+06]
 [1.41456469e+06]
 [5.58122800e+06]
 [4.22291625e+06]
 [2.93679764e+06]
 [1.57859690e+06]
 [4.83632671e+06]
 [3.47813767e+06]
 [4.91807423e+06]
 [3.56000256e+06]
 [4.09124604e+06]
 [2.73341093e+06]
 [5.08163305e+06]
 [3.72382239e+06]
 [3.34614771e+06]
 [1.98830924e+06]
 [4.33707347e+06]
 [2.97904828e+06]
 [5.32765194e+06]
 [3.96984937e+06]
 [4.50080220e+06]
 [3.14296810e+06]
 [4.80811307e+06]
 [3.45051900e+06]
 [3.07263636e+06]
 [1.71479138e+06]
 [4.06332497e+06]
 [2.70540154e+06]
 [5.05395685e+06]
 [3.69633694e+06]
 [4.22725209e+06]
 [2.86953182e+06]
 [6.12662156e+06]
 [4.76906817e+06]
 [3.48225552e+06]
 [2.12475723e+06]
 [5.38107384e+06]
 [4.02407430e+06]
 [3.64561244e+06]
 [2.28858045e+06]
 [4.63636837e+06]
 [3.27929363e+06]
 [5.62694461e+06]
 [4.26985743e+06]
 [5.70891297e+06]
 [4.35192974e+06]
 [5.10750681e+06]
 [3.75065008e+06]
 [3.37184166e+06]
 [2.01470688e+06]
 [4.36282905e+06]
 [3.00584165e+06]
 [5.35334676e+06]
 [3.99625328e+06]
 [5.43516407e+06]
 [4.07814123e+06]
 [6.42604060e+06]
 [5.06902632e+06]
 [4.69031462e+06]
 [3.33353075e+06]
 [5.68070015e+06]
 [4.32377346e+06]
 [3.94513686e+06]
 [2.58844729e+06]
 [4.93605591e+06]
 [3.57902892e+06]
 [5.92658410e+06]
 [4.56986510e+06]
 [6.00852609e+06]
 [4.65170135e+06]
 [5.40695828e+06]
 [4.05033857e+06]
 [3.67138128e+06]
 [2.31443637e+06]
 [6.47953474e+06]
 [5.12300460e+06]
 [1.99721738e+07]
 [1.72301532e+07]
 [2.08352443e+07]
 [2.15753294e+07]
 [2.28421539e+07]
 [1.70451382e+07]
 [2.04394612e+07]
 [1.85715619e+07]
 [2.16617710e+07]
 [2.04855954e+07]
 [1.95064113e+07]
 [1.97823795e+07]
 [2.31535843e+07]
 [1.62820723e+07]
 [1.93536965e+07]
 [2.30454353e+07]
 [2.19700351e+07]
 [2.48044669e+07]
 [2.37083745e+07]
 [2.15264306e+07]
 [2.37497607e+07]
 [2.41263436e+07]
 [2.11673822e+07]
 [2.68319741e+07]
 [2.44220390e+07]
 [2.05154566e+07]
 [2.56681803e+07]
 [2.90707839e+07]
 [2.72675988e+07]
 [2.96513818e+07]
 [2.24154223e+07]
 [2.74336175e+07]
 [2.81411723e+07]
 [2.64343278e+07]
 [2.65769123e+07]
 [3.37724305e+07]
 [2.22181708e+07]
 [2.57892190e+07]
 [3.30298043e+07]
 [7.98480922e+06]
 [7.00372479e+06]
 [7.12346225e+06]
 [6.11760251e+06]
 [8.14069335e+06]
 [7.13801967e+06]
 [8.24480111e+06]
 [7.30516878e+06]
 [9.23212123e+06]
 [8.27719481e+06]
 [7.54827400e+06]
 [6.61582441e+06]
 [7.53509790e+06]
 [6.59789744e+06]
 [8.52434710e+06]
 [7.51516278e+06]
 [7.71548287e+06]
 [6.76872680e+06]
 [7.82957720e+06]
 [6.89375172e+06]
 [7.92966775e+06]
 [7.05907950e+06]
 [9.83714517e+06]
 [8.97397823e+06]
 [8.25039407e+06]
 [7.29634240e+06]
 [7.42961931e+06]
 [6.48515147e+06]
 [7.55088099e+06]
 [6.63970514e+06]
 [9.45936913e+06]
 [8.57653944e+06]
 [9.50188234e+06]
 [8.65754700e+06]
 [7.78385809e+06]
 [6.88742224e+06]
 [7.88621121e+06]
 [7.10843420e+06]
 [8.82475541e+06]
 [7.88644676e+06]
 [8.04059980e+06]
 [7.17008337e+06]
 [8.11739006e+06]
 [7.25169120e+06]
 [8.20063709e+06]
 [7.52092499e+06]
 [1.00997184e+07]
 [9.33817182e+06]
 [8.59583302e+06]
 [7.74388397e+06]
 [7.67929440e+06]
 [6.79622358e+06]
 [7.82279178e+06]
 [7.01140982e+06]
 [9.72815286e+06]
 [8.99041706e+06]
 [9.76853947e+06]
 [8.89936468e+06]
 [8.06249501e+06]
 [7.23495188e+06]
 [8.18820485e+06]
 [7.46270792e+06]
 [9.08136440e+06]
 [8.12963943e+06]
 [8.31751798e+06]
 [7.48147871e+06]
 [8.38970103e+06]
 [7.56326354e+06]
 [1.41373189e+07]
 [1.25357292e+07]
 [1.55837946e+07]
 [1.41959711e+07]
 [1.71212260e+07]
 [1.49388765e+07]
 [1.39909896e+07]
 [1.41068727e+07]
 [1.48163467e+07]
 [1.45209613e+07]
 [1.62255445e+07]
 [1.79107373e+07]
 [1.57432900e+07]
 [1.30012115e+07]
 [1.46912683e+07]
 [1.73592937e+07]
 [1.56135044e+07]
 [1.71244450e+07]
 [1.45810305e+07]
 [1.43189120e+07]
 [1.55243113e+07]
 [1.41926094e+07]
 [1.53078953e+07]
 [1.86487452e+07]
 [1.62628334e+07]
 [1.40454978e+07]
 [1.50022608e+07]
 [1.74526740e+07]
 [1.68841145e+07]
 [1.69020931e+07]
 [1.47003370e+07]
 [1.48296759e+07]
 [1.49487391e+07]
 [1.61467090e+07]]

## Preprocessing test set data(same as test set)
I got stuck for a while during preprocessing as the promotional expenses data was incomplete so on merging the data my test set examples got reduced. As the data was missing at only few places I filled it myself.(Could have done better)

In [39]:
test=pd.read_csv('yds_test2018.csv')
test=test.drop(columns=['Sales'])
print(list(test))
#df_expenses.columns=['Year','Month','Country','Product_ID','Expense_Price']
#print(df_expenses)
print(test.shape)
#print(df_expenses.loc[df_expenses.Year>=2016,'Year'].shape)
test_merge=df_expenses.merge(test,how='inner',on=['Year','Month','Product_ID','Country'])
test_merge=test_merge.drop(columns=['S_No'])
#print(test_merge[:5])
print(test_merge.shape)
test_merge.to_csv('missing.csv')

['S_No', 'Year', 'Month', 'Product_ID', 'Country']
(105, 5)
(105, 5)
Empty DataFrame
Columns: [Year, Month, Country, Product_ID, Expense_Price]
Index: []

In [40]:
test_merge=test_merge.merge(holidays_count,how='inner',on=['Year','Month','Country'])
#holidays_count.to_csv('missing_holidays.csv',ignore_index=True)
print(test_merge.head())

     Year  Month    Country  Product_ID  Expense_Price  no_of_holidays
0    2016      4  Argentina           1       8214.875               1
1    2016      4  Argentina           2       3087.389               1
2    2016      5  Argentina           1      10777.878               2
3    2016      5  Argentina           2       3424.024               2
4    2016      6  Argentina           1      10320.673               2
5    2016      6  Argentina           2       3544.379               2
6    2016      7  Argentina           1       7377.587               1
7    2016      7  Argentina           2       3303.667               1
8    2016      8  Argentina           1       9805.705               1
9    2016      8  Argentina           2       3828.908               1
10   2016      9  Argentina           1       9375.481               0
11   2016      9  Argentina           2       3415.876               0
12   2016     10  Argentina           1       7284.900               1
13   2016     10  Argentina           2       3367.186               1
14   2016     11  Argentina           1      10381.438               1
15   2016     11  Argentina           2       3567.157               1
16   2016     12  Argentina           1       6865.382               2
17   2016     12  Argentina           2       3616.041               2
18   2017      1  Argentina           1      10704.394               1
19   2017      1  Argentina           2       3652.529               1
20   2017      1  Argentina           3       6000.000               1
21   2017      2  Argentina           1       7253.269               2
22   2017      2  Argentina           2       3250.009               2
23   2017      2  Argentina           3       6555.000               2
24   2017      3  Argentina           1       8427.013               1
25   2017      3  Argentina           3       5555.000               1
26   2017      3  Argentina           2       2951.466               1
27   2016      4    Belgium           2        765.271               0
28   2016      5    Belgium           2        622.565               4
29   2016      6    Belgium           2        722.112               0
..    ...    ...        ...         ...            ...             ...
75   2017      1    Denmark           2      61985.791               1
76   2017      2    Denmark           2      57087.558               0
77   2017      3    Denmark           2      67228.892               0
78   2015     11    England           4        171.166               0
79   2015     11    England           5        416.969               0
80   2015     12    England           4        194.468               3
81   2015     12    England           5        464.351               3
82   2016      1    England           4        162.639               1
83   2016      1    England           5        349.703               1
84   2016      2    England           4        163.553               0
85   2016      2    England           5        333.141               0
86   2016      3    England           4        174.685               2
87   2016      3    England           5        427.817               2
88   2016      4    England           4        172.181               0
89   2016      4    England           5        399.159               0
90   2016      5    England           4        175.224               2
91   2016      5    England           5        400.744               2
92   2016      6    England           4        181.402               0
93   2016      6    England           5        426.198               0
94   2016      7    England           4        157.756               0
95   2016      7    England           5        378.903               0
96   2015     11    Finland           4       1306.731               0
97   2015     12    Finland           4       1499.447               4
98   2016      1    Finland           4       1181.306               2
99   2016      2    Finland           4        940.191               0
100  2016      3    Finland           4       1439.734               3
101  2016      4    Finland           4       1378.859               0
102  2016      5    Finland           4        970.194               3
103  2016      6    Finland           4       1289.024               2
104  2016      7    Finland           4        900.083               0

[105 rows x 6 columns]

In [41]:
test_merge.loc[test_merge.Year==2016,'Year']=4
test_merge.loc[test_merge.Year==2017,'Year']=5
test_merge.loc[test_merge.Year==2018,'Year']=6
test_merge.loc[test_merge.Country=='Argentina','Country']=1
test_merge.loc[test_merge.Country=='Belgium','Country']=2
test_merge.loc[test_merge.Country=='Columbia','Country']=3
test_merge.loc[test_merge.Country=='Denmark','Country']=4
test_merge.loc[test_merge.Country=='England','Country']=5
test_merge.loc[test_merge.Country=='Finland','Country']=6
print(test_merge)

     Year  Month  Country  Product_ID  Expense_Price  no_of_holidays
0       4      4        1           1       8214.875               1
1       4      4        1           2       3087.389               1
2       4      5        1           1      10777.878               2
3       4      5        1           2       3424.024               2
4       4      6        1           1      10320.673               2
5       4      6        1           2       3544.379               2
6       4      7        1           1       7377.587               1
7       4      7        1           2       3303.667               1
8       4      8        1           1       9805.705               1
9       4      8        1           2       3828.908               1
10      4      9        1           1       9375.481               0
11      4      9        1           2       3415.876               0
12      4     10        1           1       7284.900               1
13      4     10        1           2       3367.186               1
14      4     11        1           1      10381.438               1
15      4     11        1           2       3567.157               1
16      4     12        1           1       6865.382               2
17      4     12        1           2       3616.041               2
18      5      1        1           1      10704.394               1
19      5      1        1           2       3652.529               1
20      5      1        1           3       6000.000               1
21      5      2        1           1       7253.269               2
22      5      2        1           2       3250.009               2
23      5      2        1           3       6555.000               2
24      5      3        1           1       8427.013               1
25      5      3        1           3       5555.000               1
26      5      3        1           2       2951.466               1
27      4      4        2           2        765.271               0
28      4      5        2           2        622.565               4
29      4      6        2           2        722.112               0
..    ...    ...      ...         ...            ...             ...
75      5      1        4           2      61985.791               1
76      5      2        4           2      57087.558               0
77      5      3        4           2      67228.892               0
78   2015     11        5           4        171.166               0
79   2015     11        5           5        416.969               0
80   2015     12        5           4        194.468               3
81   2015     12        5           5        464.351               3
82      4      1        5           4        162.639               1
83      4      1        5           5        349.703               1
84      4      2        5           4        163.553               0
85      4      2        5           5        333.141               0
86      4      3        5           4        174.685               2
87      4      3        5           5        427.817               2
88      4      4        5           4        172.181               0
89      4      4        5           5        399.159               0
90      4      5        5           4        175.224               2
91      4      5        5           5        400.744               2
92      4      6        5           4        181.402               0
93      4      6        5           5        426.198               0
94      4      7        5           4        157.756               0
95      4      7        5           5        378.903               0
96   2015     11        6           4       1306.731               0
97   2015     12        6           4       1499.447               4
98      4      1        6           4       1181.306               2
99      4      2        6           4        940.191               0
100     4      3        6           4       1439.734               3
101     4      4        6           4       1378.859               0
102     4      5        6           4        970.194               3
103     4      6        6           4       1289.024               2
104     4      7        6           4        900.083               0

[105 rows x 6 columns]

Converting expenses to USD.

In [42]:
#df_merged_expenses.loc[df_merged_expenses.Country==1,'Sales_sum']*=0.036
test_merge.loc[test_merge.Country==1,'Expense_Price']*=0.036
#df_merged_expenses.loc[df_merged_expenses.Country==2,'Sales_sum']=1.17
test_merge.loc[test_merge.Country==2,'Expense_Price']*=1.17
#df_merged_expenses.loc[df_merged_expenses.Country==3,'Sales_sum']*=0.00035
test_merge.loc[test_merge.Country==3,'Expense_Price']*=0.00035
#df_merged_expenses.loc[df_merged_expenses.Country==4,'Sales_sum']/=0.16
test_merge.loc[test_merge.Country==4,'Expense_Price']*=0.16
#df_merged_expenses.loc[df_merged_expenses.Country==5,'Sales_sum']*=1.31
test_merge.loc[test_merge.Country==5,'Expense_Price']*=1.31
#df_merged_expenses.loc[df_merged_expenses.Country==6,'Sales_sum']*=1.17
test_merge.loc[test_merge.Country==6,'Expense_Price']*=1.17

In [43]:
#print(test_merge)
#scale_parameter=scaler.scale_
X=test_merge.values.ravel()
print(X.shape)
X=X.reshape(-1,6)
#X=X*scale_parameter
print(X)

(630,)
[[4.00000000e+00 4.00000000e+00 1.00000000e+00 1.00000000e+00
  2.95735500e+02 1.00000000e+00]
 [4.00000000e+00 4.00000000e+00 1.00000000e+00 2.00000000e+00
  1.11146004e+02 1.00000000e+00]
 [4.00000000e+00 5.00000000e+00 1.00000000e+00 1.00000000e+00
  3.88003608e+02 2.00000000e+00]
 [4.00000000e+00 5.00000000e+00 1.00000000e+00 2.00000000e+00
  1.23264864e+02 2.00000000e+00]
 [4.00000000e+00 6.00000000e+00 1.00000000e+00 1.00000000e+00
  3.71544228e+02 2.00000000e+00]
 [4.00000000e+00 6.00000000e+00 1.00000000e+00 2.00000000e+00
  1.27597644e+02 2.00000000e+00]
 [4.00000000e+00 7.00000000e+00 1.00000000e+00 1.00000000e+00
  2.65593132e+02 1.00000000e+00]
 [4.00000000e+00 7.00000000e+00 1.00000000e+00 2.00000000e+00
  1.18932012e+02 1.00000000e+00]
 [4.00000000e+00 8.00000000e+00 1.00000000e+00 1.00000000e+00
  3.53005380e+02 1.00000000e+00]
 [4.00000000e+00 8.00000000e+00 1.00000000e+00 2.00000000e+00
  1.37840688e+02 1.00000000e+00]
 [4.00000000e+00 9.00000000e+00 1.00000000e+00 1.00000000e+00
  3.37517316e+02 0.00000000e+00]
 [4.00000000e+00 9.00000000e+00 1.00000000e+00 2.00000000e+00
  1.22971536e+02 0.00000000e+00]
 [4.00000000e+00 1.00000000e+01 1.00000000e+00 1.00000000e+00
  2.62256400e+02 1.00000000e+00]
 [4.00000000e+00 1.00000000e+01 1.00000000e+00 2.00000000e+00
  1.21218696e+02 1.00000000e+00]
 [4.00000000e+00 1.10000000e+01 1.00000000e+00 1.00000000e+00
  3.73731768e+02 1.00000000e+00]
 [4.00000000e+00 1.10000000e+01 1.00000000e+00 2.00000000e+00
  1.28417652e+02 1.00000000e+00]
 [4.00000000e+00 1.20000000e+01 1.00000000e+00 1.00000000e+00
  2.47153752e+02 2.00000000e+00]
 [4.00000000e+00 1.20000000e+01 1.00000000e+00 2.00000000e+00
  1.30177476e+02 2.00000000e+00]
 [5.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  3.85358184e+02 1.00000000e+00]
 [5.00000000e+00 1.00000000e+00 1.00000000e+00 2.00000000e+00
  1.31491044e+02 1.00000000e+00]
 [5.00000000e+00 1.00000000e+00 1.00000000e+00 3.00000000e+00
  2.16000000e+02 1.00000000e+00]
 [5.00000000e+00 2.00000000e+00 1.00000000e+00 1.00000000e+00
  2.61117684e+02 2.00000000e+00]
 [5.00000000e+00 2.00000000e+00 1.00000000e+00 2.00000000e+00
  1.17000324e+02 2.00000000e+00]
 [5.00000000e+00 2.00000000e+00 1.00000000e+00 3.00000000e+00
  2.35980000e+02 2.00000000e+00]
 [5.00000000e+00 3.00000000e+00 1.00000000e+00 1.00000000e+00
  3.03372468e+02 1.00000000e+00]
 [5.00000000e+00 3.00000000e+00 1.00000000e+00 3.00000000e+00
  1.99980000e+02 1.00000000e+00]
 [5.00000000e+00 3.00000000e+00 1.00000000e+00 2.00000000e+00
  1.06252776e+02 1.00000000e+00]
 [4.00000000e+00 4.00000000e+00 2.00000000e+00 2.00000000e+00
  8.95367070e+02 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 2.00000000e+00 2.00000000e+00
  7.28401050e+02 4.00000000e+00]
 [4.00000000e+00 6.00000000e+00 2.00000000e+00 2.00000000e+00
  8.44871040e+02 0.00000000e+00]
 [4.00000000e+00 7.00000000e+00 2.00000000e+00 2.00000000e+00
  7.91648910e+02 1.00000000e+00]
 [4.00000000e+00 8.00000000e+00 2.00000000e+00 2.00000000e+00
  7.76795760e+02 1.00000000e+00]
 [4.00000000e+00 9.00000000e+00 2.00000000e+00 2.00000000e+00
  8.90367660e+02 0.00000000e+00]
 [4.00000000e+00 1.00000000e+01 2.00000000e+00 2.00000000e+00
  9.98996310e+02 0.00000000e+00]
 [4.00000000e+00 1.10000000e+01 2.00000000e+00 2.00000000e+00
  9.02678400e+02 2.00000000e+00]
 [4.00000000e+00 1.20000000e+01 2.00000000e+00 2.00000000e+00
  9.70133580e+02 1.00000000e+00]
 [5.00000000e+00 1.00000000e+00 2.00000000e+00 2.00000000e+00
  8.49587310e+02 1.00000000e+00]
 [5.00000000e+00 2.00000000e+00 2.00000000e+00 2.00000000e+00
  7.22278440e+02 0.00000000e+00]
 [5.00000000e+00 3.00000000e+00 2.00000000e+00 2.00000000e+00
  5.81761440e+02 0.00000000e+00]
 [4.00000000e+00 4.00000000e+00 3.00000000e+00 1.00000000e+00
  6.03272250e-01 0.00000000e+00]
 [4.00000000e+00 4.00000000e+00 3.00000000e+00 2.00000000e+00
  1.14196705e+00 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 3.00000000e+00 1.00000000e+00
  5.56394650e-01 3.00000000e+00]
 [4.00000000e+00 5.00000000e+00 3.00000000e+00 2.00000000e+00
  1.21946195e+00 3.00000000e+00]
 [4.00000000e+00 6.00000000e+00 3.00000000e+00 1.00000000e+00
  6.27318650e-01 1.00000000e+00]
 [4.00000000e+00 6.00000000e+00 3.00000000e+00 2.00000000e+00
  1.23407095e+00 1.00000000e+00]
 [4.00000000e+00 7.00000000e+00 3.00000000e+00 1.00000000e+00
  5.45849500e-01 2.00000000e+00]
 [4.00000000e+00 7.00000000e+00 3.00000000e+00 2.00000000e+00
  1.34966825e+00 2.00000000e+00]
 [4.00000000e+00 8.00000000e+00 3.00000000e+00 1.00000000e+00
  4.76027300e-01 2.00000000e+00]
 [4.00000000e+00 8.00000000e+00 3.00000000e+00 2.00000000e+00
  1.10974570e+00 2.00000000e+00]
 [4.00000000e+00 9.00000000e+00 3.00000000e+00 1.00000000e+00
  5.62876650e-01 0.00000000e+00]
 [4.00000000e+00 9.00000000e+00 3.00000000e+00 2.00000000e+00
  1.25686225e+00 0.00000000e+00]
 [4.00000000e+00 1.00000000e+01 3.00000000e+00 1.00000000e+00
  5.33943900e-01 1.00000000e+00]
 [4.00000000e+00 1.00000000e+01 3.00000000e+00 2.00000000e+00
  1.23433625e+00 1.00000000e+00]
 [4.00000000e+00 1.10000000e+01 3.00000000e+00 1.00000000e+00
  5.92022900e-01 2.00000000e+00]
 [4.00000000e+00 1.10000000e+01 3.00000000e+00 2.00000000e+00
  1.30497220e+00 2.00000000e+00]
 [4.00000000e+00 1.20000000e+01 3.00000000e+00 1.00000000e+00
  5.81262500e-01 2.00000000e+00]
 [4.00000000e+00 1.20000000e+01 3.00000000e+00 2.00000000e+00
  1.20921605e+00 2.00000000e+00]
 [5.00000000e+00 1.00000000e+00 3.00000000e+00 1.00000000e+00
  5.15259850e-01 1.00000000e+00]
 [5.00000000e+00 1.00000000e+00 3.00000000e+00 2.00000000e+00
  1.30830000e+00 1.00000000e+00]
 [5.00000000e+00 1.00000000e+00 3.00000000e+00 3.00000000e+00
  7.35000000e-01 1.00000000e+00]
 [5.00000000e+00 2.00000000e+00 3.00000000e+00 1.00000000e+00
  5.40417850e-01 0.00000000e+00]
 [5.00000000e+00 2.00000000e+00 3.00000000e+00 2.00000000e+00
  1.15610880e+00 0.00000000e+00]
 [5.00000000e+00 2.00000000e+00 3.00000000e+00 3.00000000e+00
  7.00000000e-01 0.00000000e+00]
 [5.00000000e+00 3.00000000e+00 3.00000000e+00 1.00000000e+00
  6.45252650e-01 1.00000000e+00]
 [5.00000000e+00 3.00000000e+00 3.00000000e+00 3.00000000e+00
  7.07700000e-01 1.00000000e+00]
 [5.00000000e+00 3.00000000e+00 3.00000000e+00 2.00000000e+00
  1.37309865e+00 1.00000000e+00]
 [4.00000000e+00 4.00000000e+00 4.00000000e+00 2.00000000e+00
  1.05880422e+04 1.00000000e+00]
 [4.00000000e+00 5.00000000e+00 4.00000000e+00 2.00000000e+00
  1.34658870e+04 3.00000000e+00]
 [4.00000000e+00 6.00000000e+00 4.00000000e+00 2.00000000e+00
  1.16974486e+04 0.00000000e+00]
 [4.00000000e+00 7.00000000e+00 4.00000000e+00 2.00000000e+00
  1.04445515e+04 0.00000000e+00]
 [4.00000000e+00 8.00000000e+00 4.00000000e+00 2.00000000e+00
  1.21503810e+04 0.00000000e+00]
 [4.00000000e+00 9.00000000e+00 4.00000000e+00 2.00000000e+00
  1.18248371e+04 0.00000000e+00]
 [4.00000000e+00 1.00000000e+01 4.00000000e+00 2.00000000e+00
  1.24963178e+04 0.00000000e+00]
 [4.00000000e+00 1.10000000e+01 4.00000000e+00 2.00000000e+00
  1.14235646e+04 0.00000000e+00]
 [4.00000000e+00 1.20000000e+01 4.00000000e+00 2.00000000e+00
  1.13271357e+04 2.00000000e+00]
 [5.00000000e+00 1.00000000e+00 4.00000000e+00 2.00000000e+00
  9.91772656e+03 1.00000000e+00]
 [5.00000000e+00 2.00000000e+00 4.00000000e+00 2.00000000e+00
  9.13400928e+03 0.00000000e+00]
 [5.00000000e+00 3.00000000e+00 4.00000000e+00 2.00000000e+00
  1.07566227e+04 0.00000000e+00]
 [2.01500000e+03 1.10000000e+01 5.00000000e+00 4.00000000e+00
  2.24227460e+02 0.00000000e+00]
 [2.01500000e+03 1.10000000e+01 5.00000000e+00 5.00000000e+00
  5.46229390e+02 0.00000000e+00]
 [2.01500000e+03 1.20000000e+01 5.00000000e+00 4.00000000e+00
  2.54753080e+02 3.00000000e+00]
 [2.01500000e+03 1.20000000e+01 5.00000000e+00 5.00000000e+00
  6.08299810e+02 3.00000000e+00]
 [4.00000000e+00 1.00000000e+00 5.00000000e+00 4.00000000e+00
  2.13057090e+02 1.00000000e+00]
 [4.00000000e+00 1.00000000e+00 5.00000000e+00 5.00000000e+00
  4.58110930e+02 1.00000000e+00]
 [4.00000000e+00 2.00000000e+00 5.00000000e+00 4.00000000e+00
  2.14254430e+02 0.00000000e+00]
 [4.00000000e+00 2.00000000e+00 5.00000000e+00 5.00000000e+00
  4.36414710e+02 0.00000000e+00]
 [4.00000000e+00 3.00000000e+00 5.00000000e+00 4.00000000e+00
  2.28837350e+02 2.00000000e+00]
 [4.00000000e+00 3.00000000e+00 5.00000000e+00 5.00000000e+00
  5.60440270e+02 2.00000000e+00]
 [4.00000000e+00 4.00000000e+00 5.00000000e+00 4.00000000e+00
  2.25557110e+02 0.00000000e+00]
 [4.00000000e+00 4.00000000e+00 5.00000000e+00 5.00000000e+00
  5.22898290e+02 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 5.00000000e+00 4.00000000e+00
  2.29543440e+02 2.00000000e+00]
 [4.00000000e+00 5.00000000e+00 5.00000000e+00 5.00000000e+00
  5.24974640e+02 2.00000000e+00]
 [4.00000000e+00 6.00000000e+00 5.00000000e+00 4.00000000e+00
  2.37636620e+02 0.00000000e+00]
 [4.00000000e+00 6.00000000e+00 5.00000000e+00 5.00000000e+00
  5.58319380e+02 0.00000000e+00]
 [4.00000000e+00 7.00000000e+00 5.00000000e+00 4.00000000e+00
  2.06660360e+02 0.00000000e+00]
 [4.00000000e+00 7.00000000e+00 5.00000000e+00 5.00000000e+00
  4.96362930e+02 0.00000000e+00]
 [2.01500000e+03 1.10000000e+01 6.00000000e+00 4.00000000e+00
  1.52887527e+03 0.00000000e+00]
 [2.01500000e+03 1.20000000e+01 6.00000000e+00 4.00000000e+00
  1.75435299e+03 4.00000000e+00]
 [4.00000000e+00 1.00000000e+00 6.00000000e+00 4.00000000e+00
  1.38212802e+03 2.00000000e+00]
 [4.00000000e+00 2.00000000e+00 6.00000000e+00 4.00000000e+00
  1.10002347e+03 0.00000000e+00]
 [4.00000000e+00 3.00000000e+00 6.00000000e+00 4.00000000e+00
  1.68448878e+03 3.00000000e+00]
 [4.00000000e+00 4.00000000e+00 6.00000000e+00 4.00000000e+00
  1.61326503e+03 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 6.00000000e+00 4.00000000e+00
  1.13512698e+03 3.00000000e+00]
 [4.00000000e+00 6.00000000e+00 6.00000000e+00 4.00000000e+00
  1.50815808e+03 2.00000000e+00]
 [4.00000000e+00 7.00000000e+00 6.00000000e+00 4.00000000e+00
  1.05309711e+03 0.00000000e+00]]

In [585]:
#outmodel.predict(X)
output=scaler2.inverse_transform(model.predict(X).reshape(-1,1))
output=np.absolute(output)
#print(output)
output_y=pd.DataFrame(output,columns=['Sales'])
print(output_y)
print(output_y.shape,X.shape)

            Sales
0    7.201995e+06
1    7.541494e+06
2    6.967340e+06
3    7.306851e+06
4    6.959896e+06
5    7.299404e+06
6    7.179660e+06
7    7.519153e+06
8    7.172200e+06
9    7.511704e+06
10   7.391951e+06
11   7.731454e+06
12   7.157321e+06
13   7.496814e+06
14   7.149858e+06
15   7.489366e+06
16   6.915236e+06
17   7.254725e+06
18   7.124472e+06
19   7.463982e+06
20   7.803440e+06
21   6.889850e+06
22   7.229343e+06
23   7.568796e+06
24   7.109592e+06
25   7.788549e+06
26   7.449093e+06
27   6.969636e+06
28   6.053438e+06
29   6.954751e+06
..            ...
75   5.065692e+06
76   5.285560e+06
77   5.277866e+06
78   1.955944e+08
79   1.952550e+08
80   1.962835e+08
81   1.959441e+08
82   5.047030e+06
83   5.386464e+06
84   5.266778e+06
85   5.606215e+06
86   4.804941e+06
87   5.144361e+06
88   5.251884e+06
89   5.591309e+06
90   4.790048e+06
91   5.129473e+06
92   5.236989e+06
93   5.576411e+06
94   5.229547e+06
95   5.568974e+06
96   1.963936e+08
97   1.973098e+08
98   4.020725e+06
99   4.467711e+06
100  3.778592e+06
101  4.452740e+06
102  3.763783e+06
103  3.983474e+06
104  4.430486e+06

[105 rows x 1 columns]
(105, 1) (105, 6)

## Time to apply model
Time for results.

In [44]:
best_random = rf_random.best_estimator_
output=best_random.predict(X).reshape(-1,1)
output=np.absolute(output)
#print(output)
output_y=pd.DataFrame(output,columns=['Sales'])
print(output_y)
print(output_y.shape,X.shape)

            Sales
0    3.921513e+05
1    2.634624e+05
2    1.328576e+06
3    2.702687e+05
4    5.420494e+05
5    2.702687e+05
6    2.845368e+05
7    2.702687e+05
8    5.245501e+05
9    2.702687e+05
10   4.725225e+05
11   2.702687e+05
12   2.603410e+05
13   2.702687e+05
14   5.593123e+05
15   2.702687e+05
16   2.702687e+05
17   2.702687e+05
18   5.353531e+05
19   2.712744e+05
20   2.712744e+05
21   2.909346e+05
22   2.703055e+05
23   2.712744e+05
24   3.980866e+05
25   2.702687e+05
26   2.634624e+05
27   1.316039e+06
28   1.316039e+06
29   1.316039e+06
..            ...
75   2.820295e+07
76   2.170900e+07
77   2.730567e+07
78   2.702687e+05
79   8.175092e+05
80   2.621915e+05
81   9.220074e+05
82   2.712744e+05
83   6.721906e+05
84   2.712744e+05
85   6.177203e+05
86   2.702687e+05
87   9.180537e+05
88   2.702687e+05
89   8.436590e+05
90   2.702687e+05
91   8.196763e+05
92   2.702687e+05
93   9.812780e+05
94   2.702687e+05
95   7.274900e+05
96   3.368600e+07
97   3.736018e+07
98   2.904784e+07
99   2.157779e+07
100  3.646658e+07
101  3.579691e+07
102  2.212838e+07
103  3.198351e+07
104  2.158766e+07

[105 rows x 1 columns]
(105, 1) (105, 6)

In [ ]:
#base_model = RandomForestRegressor(n_estimators = 10, random_state = 42)
#base_model.fit(train_features, train_labels)
#base_accuracy = evaluate(base_model, test_features, test_labels)


#random_accuracy = evaluate(best_random, test_features, test_labels)
#print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

In [45]:
output_final=pd.concat([test_merge,output_y],axis=1)
print(output_final)

     Year  Month  Country  Product_ID  Expense_Price  no_of_holidays  \
0       4      4        1           1     295.735500               1
1       4      4        1           2     111.146004               1
2       4      5        1           1     388.003608               2
3       4      5        1           2     123.264864               2
4       4      6        1           1     371.544228               2
5       4      6        1           2     127.597644               2
6       4      7        1           1     265.593132               1
7       4      7        1           2     118.932012               1
8       4      8        1           1     353.005380               1
9       4      8        1           2     137.840688               1
10      4      9        1           1     337.517316               0
11      4      9        1           2     122.971536               0
12      4     10        1           1     262.256400               1
13      4     10        1           2     121.218696               1
14      4     11        1           1     373.731768               1
15      4     11        1           2     128.417652               1
16      4     12        1           1     247.153752               2
17      4     12        1           2     130.177476               2
18      5      1        1           1     385.358184               1
19      5      1        1           2     131.491044               1
20      5      1        1           3     216.000000               1
21      5      2        1           1     261.117684               2
22      5      2        1           2     117.000324               2
23      5      2        1           3     235.980000               2
24      5      3        1           1     303.372468               1
25      5      3        1           3     199.980000               1
26      5      3        1           2     106.252776               1
27      4      4        2           2     895.367070               0
28      4      5        2           2     728.401050               4
29      4      6        2           2     844.871040               0
..    ...    ...      ...         ...            ...             ...
75      5      1        4           2    9917.726560               1
76      5      2        4           2    9134.009280               0
77      5      3        4           2   10756.622720               0
78   2015     11        5           4     224.227460               0
79   2015     11        5           5     546.229390               0
80   2015     12        5           4     254.753080               3
81   2015     12        5           5     608.299810               3
82      4      1        5           4     213.057090               1
83      4      1        5           5     458.110930               1
84      4      2        5           4     214.254430               0
85      4      2        5           5     436.414710               0
86      4      3        5           4     228.837350               2
87      4      3        5           5     560.440270               2
88      4      4        5           4     225.557110               0
89      4      4        5           5     522.898290               0
90      4      5        5           4     229.543440               2
91      4      5        5           5     524.974640               2
92      4      6        5           4     237.636620               0
93      4      6        5           5     558.319380               0
94      4      7        5           4     206.660360               0
95      4      7        5           5     496.362930               0
96   2015     11        6           4    1528.875270               0
97   2015     12        6           4    1754.352990               4
98      4      1        6           4    1382.128020               2
99      4      2        6           4    1100.023470               0
100     4      3        6           4    1684.488780               3
101     4      4        6           4    1613.265030               0
102     4      5        6           4    1135.126980               3
103     4      6        6           4    1508.158080               2
104     4      7        6           4    1053.097110               0

            Sales
0    3.921513e+05
1    2.634624e+05
2    1.328576e+06
3    2.702687e+05
4    5.420494e+05
5    2.702687e+05
6    2.845368e+05
7    2.702687e+05
8    5.245501e+05
9    2.702687e+05
10   4.725225e+05
11   2.702687e+05
12   2.603410e+05
13   2.702687e+05
14   5.593123e+05
15   2.702687e+05
16   2.702687e+05
17   2.702687e+05
18   5.353531e+05
19   2.712744e+05
20   2.712744e+05
21   2.909346e+05
22   2.703055e+05
23   2.712744e+05
24   3.980866e+05
25   2.702687e+05
26   2.634624e+05
27   1.316039e+06
28   1.316039e+06
29   1.316039e+06
..            ...
75   2.820295e+07
76   2.170900e+07
77   2.730567e+07
78   2.702687e+05
79   8.175092e+05
80   2.621915e+05
81   9.220074e+05
82   2.712744e+05
83   6.721906e+05
84   2.712744e+05
85   6.177203e+05
86   2.702687e+05
87   9.180537e+05
88   2.702687e+05
89   8.436590e+05
90   2.702687e+05
91   8.196763e+05
92   2.702687e+05
93   9.812780e+05
94   2.702687e+05
95   7.274900e+05
96   3.368600e+07
97   3.736018e+07
98   2.904784e+07
99   2.157779e+07
100  3.646658e+07
101  3.579691e+07
102  2.212838e+07
103  3.198351e+07
104  2.158766e+07

[105 rows x 7 columns]

Rescaling back to local prices.

In [46]:
output_final.loc[output_final.Country==1,'Sales']/=0.036
output_final.loc[output_final.Country==1,'Expense_Price']/=0.036
output_final.loc[output_final.Country==2,'Sales']/=1.17
output_final.loc[output_final.Country==2,'Expense_Price']/=1.17
output_final.loc[output_final.Country==3,'Sales']/=0.00035
output_final.loc[output_final.Country==3,'Expense_Price']/=0.00035
output_final.loc[output_final.Country==4,'Sales']/=0.16
output_final.loc[output_final.Country==4,'Expense_Price']/=0.16
output_final.loc[output_final.Country==5,'Sales']/=1.31
output_final.loc[output_final.Country==5,'Expense_Price']/=1.31
output_final.loc[output_final.Country==6,'Sales']/=1.17
output_final.loc[output_final.Country==6,'Expense_Price']/=1.17
print(output_final)

     Year  Month  Country  Product_ID  Expense_Price  no_of_holidays  \
0       4      4        1           1       8214.875               1
1       4      4        1           2       3087.389               1
2       4      5        1           1      10777.878               2
3       4      5        1           2       3424.024               2
4       4      6        1           1      10320.673               2
5       4      6        1           2       3544.379               2
6       4      7        1           1       7377.587               1
7       4      7        1           2       3303.667               1
8       4      8        1           1       9805.705               1
9       4      8        1           2       3828.908               1
10      4      9        1           1       9375.481               0
11      4      9        1           2       3415.876               0
12      4     10        1           1       7284.900               1
13      4     10        1           2       3367.186               1
14      4     11        1           1      10381.438               1
15      4     11        1           2       3567.157               1
16      4     12        1           1       6865.382               2
17      4     12        1           2       3616.041               2
18      5      1        1           1      10704.394               1
19      5      1        1           2       3652.529               1
20      5      1        1           3       6000.000               1
21      5      2        1           1       7253.269               2
22      5      2        1           2       3250.009               2
23      5      2        1           3       6555.000               2
24      5      3        1           1       8427.013               1
25      5      3        1           3       5555.000               1
26      5      3        1           2       2951.466               1
27      4      4        2           2        765.271               0
28      4      5        2           2        622.565               4
29      4      6        2           2        722.112               0
..    ...    ...      ...         ...            ...             ...
75      5      1        4           2      61985.791               1
76      5      2        4           2      57087.558               0
77      5      3        4           2      67228.892               0
78   2015     11        5           4        171.166               0
79   2015     11        5           5        416.969               0
80   2015     12        5           4        194.468               3
81   2015     12        5           5        464.351               3
82      4      1        5           4        162.639               1
83      4      1        5           5        349.703               1
84      4      2        5           4        163.553               0
85      4      2        5           5        333.141               0
86      4      3        5           4        174.685               2
87      4      3        5           5        427.817               2
88      4      4        5           4        172.181               0
89      4      4        5           5        399.159               0
90      4      5        5           4        175.224               2
91      4      5        5           5        400.744               2
92      4      6        5           4        181.402               0
93      4      6        5           5        426.198               0
94      4      7        5           4        157.756               0
95      4      7        5           5        378.903               0
96   2015     11        6           4       1306.731               0
97   2015     12        6           4       1499.447               4
98      4      1        6           4       1181.306               2
99      4      2        6           4        940.191               0
100     4      3        6           4       1439.734               3
101     4      4        6           4       1378.859               0
102     4      5        6           4        970.194               3
103     4      6        6           4       1289.024               2
104     4      7        6           4        900.083               0

            Sales
0    1.089309e+07
1    7.318399e+06
2    3.690488e+07
3    7.507463e+06
4    1.505693e+07
5    7.507463e+06
6    7.903801e+06
7    7.507463e+06
8    1.457084e+07
9    7.507463e+06
10   1.312562e+07
11   7.507463e+06
12   7.231693e+06
13   7.507463e+06
14   1.553645e+07
15   7.507463e+06
16   7.507463e+06
17   7.507463e+06
18   1.487092e+07
19   7.535399e+06
20   7.535399e+06
21   8.081516e+06
22   7.508486e+06
23   7.535399e+06
24   1.105796e+07
25   7.507463e+06
26   7.318399e+06
27   1.124820e+06
28   1.124820e+06
29   1.124820e+06
..            ...
75   1.762685e+08
76   1.356813e+08
77   1.706605e+08
78   2.063120e+05
79   6.240528e+05
80   2.001462e+05
81   7.038224e+05
82   2.070797e+05
83   5.131226e+05
84   2.070797e+05
85   4.715422e+05
86   2.063120e+05
87   7.008043e+05
88   2.063120e+05
89   6.440145e+05
90   2.063120e+05
91   6.257071e+05
92   2.063120e+05
93   7.490672e+05
94   2.063120e+05
95   5.553359e+05
96   2.879146e+07
97   3.193178e+07
98   2.482721e+07
99   1.844256e+07
100  3.116801e+07
101  3.059565e+07
102  1.891314e+07
103  2.733633e+07
104  1.845099e+07

[105 rows x 7 columns]

Re converting numerical features to categorical.

In [47]:
output_final.loc[output_final.Year==4,'Year']=2016
output_final.loc[output_final.Year==5,'Year']=2017
output_final.loc[output_final.Year==46,'Year']=2018
output_final.loc[output_final.Country==1,'Country']='Argentina'
output_final.loc[output_final.Country==2,'Country']='Belgium'
output_final.loc[output_final.Country==3,'Country']='Columbia'
output_final.loc[output_final.Country==4,'Country']='Denmark'
output_final.loc[output_final.Country==5,'Country']='England'
output_final.loc[output_final.Country==6,'Country']='Finland'
print(output_final)

     Year  Month    Country  Product_ID  Expense_Price  no_of_holidays  \
0    2016      4  Argentina           1       8214.875               1
1    2016      4  Argentina           2       3087.389               1
2    2016      5  Argentina           1      10777.878               2
3    2016      5  Argentina           2       3424.024               2
4    2016      6  Argentina           1      10320.673               2
5    2016      6  Argentina           2       3544.379               2
6    2016      7  Argentina           1       7377.587               1
7    2016      7  Argentina           2       3303.667               1
8    2016      8  Argentina           1       9805.705               1
9    2016      8  Argentina           2       3828.908               1
10   2016      9  Argentina           1       9375.481               0
11   2016      9  Argentina           2       3415.876               0
12   2016     10  Argentina           1       7284.900               1
13   2016     10  Argentina           2       3367.186               1
14   2016     11  Argentina           1      10381.438               1
15   2016     11  Argentina           2       3567.157               1
16   2016     12  Argentina           1       6865.382               2
17   2016     12  Argentina           2       3616.041               2
18   2017      1  Argentina           1      10704.394               1
19   2017      1  Argentina           2       3652.529               1
20   2017      1  Argentina           3       6000.000               1
21   2017      2  Argentina           1       7253.269               2
22   2017      2  Argentina           2       3250.009               2
23   2017      2  Argentina           3       6555.000               2
24   2017      3  Argentina           1       8427.013               1
25   2017      3  Argentina           3       5555.000               1
26   2017      3  Argentina           2       2951.466               1
27   2016      4    Belgium           2        765.271               0
28   2016      5    Belgium           2        622.565               4
29   2016      6    Belgium           2        722.112               0
..    ...    ...        ...         ...            ...             ...
75   2017      1    Denmark           2      61985.791               1
76   2017      2    Denmark           2      57087.558               0
77   2017      3    Denmark           2      67228.892               0
78   2015     11    England           4        171.166               0
79   2015     11    England           5        416.969               0
80   2015     12    England           4        194.468               3
81   2015     12    England           5        464.351               3
82   2016      1    England           4        162.639               1
83   2016      1    England           5        349.703               1
84   2016      2    England           4        163.553               0
85   2016      2    England           5        333.141               0
86   2016      3    England           4        174.685               2
87   2016      3    England           5        427.817               2
88   2016      4    England           4        172.181               0
89   2016      4    England           5        399.159               0
90   2016      5    England           4        175.224               2
91   2016      5    England           5        400.744               2
92   2016      6    England           4        181.402               0
93   2016      6    England           5        426.198               0
94   2016      7    England           4        157.756               0
95   2016      7    England           5        378.903               0
96   2015     11    Finland           4       1306.731               0
97   2015     12    Finland           4       1499.447               4
98   2016      1    Finland           4       1181.306               2
99   2016      2    Finland           4        940.191               0
100  2016      3    Finland           4       1439.734               3
101  2016      4    Finland           4       1378.859               0
102  2016      5    Finland           4        970.194               3
103  2016      6    Finland           4       1289.024               2
104  2016      7    Finland           4        900.083               0

            Sales
0    1.089309e+07
1    7.318399e+06
2    3.690488e+07
3    7.507463e+06
4    1.505693e+07
5    7.507463e+06
6    7.903801e+06
7    7.507463e+06
8    1.457084e+07
9    7.507463e+06
10   1.312562e+07
11   7.507463e+06
12   7.231693e+06
13   7.507463e+06
14   1.553645e+07
15   7.507463e+06
16   7.507463e+06
17   7.507463e+06
18   1.487092e+07
19   7.535399e+06
20   7.535399e+06
21   8.081516e+06
22   7.508486e+06
23   7.535399e+06
24   1.105796e+07
25   7.507463e+06
26   7.318399e+06
27   1.124820e+06
28   1.124820e+06
29   1.124820e+06
..            ...
75   1.762685e+08
76   1.356813e+08
77   1.706605e+08
78   2.063120e+05
79   6.240528e+05
80   2.001462e+05
81   7.038224e+05
82   2.070797e+05
83   5.131226e+05
84   2.070797e+05
85   4.715422e+05
86   2.063120e+05
87   7.008043e+05
88   2.063120e+05
89   6.440145e+05
90   2.063120e+05
91   6.257071e+05
92   2.063120e+05
93   7.490672e+05
94   2.063120e+05
95   5.553359e+05
96   2.879146e+07
97   3.193178e+07
98   2.482721e+07
99   1.844256e+07
100  3.116801e+07
101  3.059565e+07
102  1.891314e+07
103  2.733633e+07
104  1.845099e+07

[105 rows x 7 columns]

You have to include Serial_no as well though it wasn't mentioned on the challenge page.

In [48]:
output_fin=output_final.merge(test,on=['Year','Month','Product_ID','Country'])
print(output_fin.head())

     Year  Month    Country  Product_ID  Expense_Price  no_of_holidays  \
0    2016      4  Argentina           1       8214.875               1
1    2016      4  Argentina           2       3087.389               1
2    2016      5  Argentina           1      10777.878               2
3    2016      5  Argentina           2       3424.024               2
4    2016      6  Argentina           1      10320.673               2
5    2016      6  Argentina           2       3544.379               2
6    2016      7  Argentina           1       7377.587               1
7    2016      7  Argentina           2       3303.667               1
8    2016      8  Argentina           1       9805.705               1
9    2016      8  Argentina           2       3828.908               1
10   2016      9  Argentina           1       9375.481               0
11   2016      9  Argentina           2       3415.876               0
12   2016     10  Argentina           1       7284.900               1
13   2016     10  Argentina           2       3367.186               1
14   2016     11  Argentina           1      10381.438               1
15   2016     11  Argentina           2       3567.157               1
16   2016     12  Argentina           1       6865.382               2
17   2016     12  Argentina           2       3616.041               2
18   2017      1  Argentina           1      10704.394               1
19   2017      1  Argentina           2       3652.529               1
20   2017      1  Argentina           3       6000.000               1
21   2017      2  Argentina           1       7253.269               2
22   2017      2  Argentina           2       3250.009               2
23   2017      2  Argentina           3       6555.000               2
24   2017      3  Argentina           1       8427.013               1
25   2017      3  Argentina           3       5555.000               1
26   2017      3  Argentina           2       2951.466               1
27   2016      4    Belgium           2        765.271               0
28   2016      5    Belgium           2        622.565               4
29   2016      6    Belgium           2        722.112               0
..    ...    ...        ...         ...            ...             ...
75   2017      1    Denmark           2      61985.791               1
76   2017      2    Denmark           2      57087.558               0
77   2017      3    Denmark           2      67228.892               0
78   2015     11    England           4        171.166               0
79   2015     11    England           5        416.969               0
80   2015     12    England           4        194.468               3
81   2015     12    England           5        464.351               3
82   2016      1    England           4        162.639               1
83   2016      1    England           5        349.703               1
84   2016      2    England           4        163.553               0
85   2016      2    England           5        333.141               0
86   2016      3    England           4        174.685               2
87   2016      3    England           5        427.817               2
88   2016      4    England           4        172.181               0
89   2016      4    England           5        399.159               0
90   2016      5    England           4        175.224               2
91   2016      5    England           5        400.744               2
92   2016      6    England           4        181.402               0
93   2016      6    England           5        426.198               0
94   2016      7    England           4        157.756               0
95   2016      7    England           5        378.903               0
96   2015     11    Finland           4       1306.731               0
97   2015     12    Finland           4       1499.447               4
98   2016      1    Finland           4       1181.306               2
99   2016      2    Finland           4        940.191               0
100  2016      3    Finland           4       1439.734               3
101  2016      4    Finland           4       1378.859               0
102  2016      5    Finland           4        970.194               3
103  2016      6    Finland           4       1289.024               2
104  2016      7    Finland           4        900.083               0

            Sales   S_No
0    1.089309e+07  79073
1    7.318399e+06  79085
2    3.690488e+07  79074
3    7.507463e+06  79086
4    1.505693e+07  79075
5    7.507463e+06  79087
6    7.903801e+06  79076
7    7.507463e+06  79088
8    1.457084e+07  79077
9    7.507463e+06  79089
10   1.312562e+07  79078
11   7.507463e+06  79090
12   7.231693e+06  79079
13   7.507463e+06  79091
14   1.553645e+07  79080
15   7.507463e+06  79092
16   7.507463e+06  79081
17   7.507463e+06  79093
18   1.487092e+07  79082
19   7.535399e+06  79094
20   7.535399e+06  79097
21   8.081516e+06  79083
22   7.508486e+06  79095
23   7.535399e+06  79098
24   1.105796e+07  79084
25   7.507463e+06  79099
26   7.318399e+06  79096
27   1.124820e+06  79100
28   1.124820e+06  79101
29   1.124820e+06  79102
..            ...    ...
75   1.762685e+08  79148
76   1.356813e+08  79149
77   1.706605e+08  79150
78   2.063120e+05  79160
79   6.240528e+05  79151
80   2.001462e+05  79161
81   7.038224e+05  79152
82   2.070797e+05  79162
83   5.131226e+05  79153
84   2.070797e+05  79163
85   4.715422e+05  79154
86   2.063120e+05  79164
87   7.008043e+05  79155
88   2.063120e+05  79165
89   6.440145e+05  79156
90   2.063120e+05  79166
91   6.257071e+05  79157
92   2.063120e+05  79167
93   7.490672e+05  79158
94   2.063120e+05  79168
95   5.553359e+05  79159
96   2.879146e+07  79169
97   3.193178e+07  79170
98   2.482721e+07  79171
99   1.844256e+07  79172
100  3.116801e+07  79173
101  3.059565e+07  79174
102  1.891314e+07  79175
103  2.733633e+07  79176
104  1.845099e+07  79177

[105 rows x 8 columns]

In [49]:
cols = output_fin.columns.tolist()
print(cols)
cols=[cols[-1]]+cols[:2]+[cols[3]]+[cols[2]]+cols[4:-1]
print(cols)

['Year', 'Month', 'Country', 'Product_ID', 'Expense_Price', 'no_of_holidays', 'Sales', 'S_No']
['S_No', 'Year', 'Month', 'Product_ID', 'Country', 'Expense_Price', 'no_of_holidays', 'Sales']

In [50]:
output_fin=output_fin[cols]
#print(output_final)
output_fin=output_fin.drop(columns=['Expense_Price','no_of_holidays'])
print(output_fin.shape)
print(output_fin.head())

(105, 6)
      S_No  Year  Month  Product_ID    Country         Sales
0    79073  2016      4           1  Argentina  1.089309e+07
1    79085  2016      4           2  Argentina  7.318399e+06
2    79074  2016      5           1  Argentina  3.690488e+07
3    79086  2016      5           2  Argentina  7.507463e+06
4    79075  2016      6           1  Argentina  1.505693e+07
5    79087  2016      6           2  Argentina  7.507463e+06
6    79076  2016      7           1  Argentina  7.903801e+06
7    79088  2016      7           2  Argentina  7.507463e+06
8    79077  2016      8           1  Argentina  1.457084e+07
9    79089  2016      8           2  Argentina  7.507463e+06
10   79078  2016      9           1  Argentina  1.312562e+07
11   79090  2016      9           2  Argentina  7.507463e+06
12   79079  2016     10           1  Argentina  7.231693e+06
13   79091  2016     10           2  Argentina  7.507463e+06
14   79080  2016     11           1  Argentina  1.553645e+07
15   79092  2016     11           2  Argentina  7.507463e+06
16   79081  2016     12           1  Argentina  7.507463e+06
17   79093  2016     12           2  Argentina  7.507463e+06
18   79082  2017      1           1  Argentina  1.487092e+07
19   79094  2017      1           2  Argentina  7.535399e+06
20   79097  2017      1           3  Argentina  7.535399e+06
21   79083  2017      2           1  Argentina  8.081516e+06
22   79095  2017      2           2  Argentina  7.508486e+06
23   79098  2017      2           3  Argentina  7.535399e+06
24   79084  2017      3           1  Argentina  1.105796e+07
25   79099  2017      3           3  Argentina  7.507463e+06
26   79096  2017      3           2  Argentina  7.318399e+06
27   79100  2016      4           2    Belgium  1.124820e+06
28   79101  2016      5           2    Belgium  1.124820e+06
29   79102  2016      6           2    Belgium  1.124820e+06
..     ...   ...    ...         ...        ...           ...
75   79148  2017      1           2    Denmark  1.762685e+08
76   79149  2017      2           2    Denmark  1.356813e+08
77   79150  2017      3           2    Denmark  1.706605e+08
78   79160  2015     11           4    England  2.063120e+05
79   79151  2015     11           5    England  6.240528e+05
80   79161  2015     12           4    England  2.001462e+05
81   79152  2015     12           5    England  7.038224e+05
82   79162  2016      1           4    England  2.070797e+05
83   79153  2016      1           5    England  5.131226e+05
84   79163  2016      2           4    England  2.070797e+05
85   79154  2016      2           5    England  4.715422e+05
86   79164  2016      3           4    England  2.063120e+05
87   79155  2016      3           5    England  7.008043e+05
88   79165  2016      4           4    England  2.063120e+05
89   79156  2016      4           5    England  6.440145e+05
90   79166  2016      5           4    England  2.063120e+05
91   79157  2016      5           5    England  6.257071e+05
92   79167  2016      6           4    England  2.063120e+05
93   79158  2016      6           5    England  7.490672e+05
94   79168  2016      7           4    England  2.063120e+05
95   79159  2016      7           5    England  5.553359e+05
96   79169  2015     11           4    Finland  2.879146e+07
97   79170  2015     12           4    Finland  3.193178e+07
98   79171  2016      1           4    Finland  2.482721e+07
99   79172  2016      2           4    Finland  1.844256e+07
100  79173  2016      3           4    Finland  3.116801e+07
101  79174  2016      4           4    Finland  3.059565e+07
102  79175  2016      5           4    Finland  1.891314e+07
103  79176  2016      6           4    Finland  2.733633e+07
104  79177  2016      7           4    Finland  1.845099e+07

[105 rows x 6 columns]

In [51]:
output_fin=output_fin.sort_values('S_No')
output_fin.to_csv('output.csv',index=False)